name: CI Checks

on:
  push:
    branches:
      - main
      - develop
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - '.gitignore'
      - 'LICENSE'
  pull_request:
    branches:
      - main
      - develop

permissions:
  contents: read

jobs:

  docker-test:
    name: Test Docker Build
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        load: true
        push: false
        tags: claude-cto:test
        cache-from: type=gha
        cache-to: type=gha,mode=max
    
    - name: Test Docker image
      run: |
        docker run --rm claude-cto:test --help
        docker run --rm claude-cto:test mcp --help

  validate-config:
    name: Validate Configuration Files
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Validate smithery.yaml
      run: |
        if ! [ -f smithery.yaml ]; then
          echo "smithery.yaml not found"
          exit 1
        fi
        # Basic YAML validation
        python -c "import yaml; yaml.safe_load(open('smithery.yaml'))"
    
    - name: Validate docker-compose.yml
      run: |
        if ! [ -f docker-compose.yml ]; then
          echo "docker-compose.yml not found"
          exit 1
        fi
        # Validate docker-compose syntax
        docker compose config > /dev/null