name: Simple Homebrew Formula Update

on:
  workflow_call:
    inputs:
      version:
        description: 'Version to update to'
        required: true
        type: string
      package_url:
        description: 'PyPI package URL'
        required: true
        type: string
      package_sha256:
        description: 'PyPI package SHA256'
        required: true
        type: string

permissions:
  contents: read

jobs:
  update-formula:
    name: Update Homebrew Formula
    runs-on: ubuntu-latest
    
    steps:
    - name: Update Homebrew tap
      env:
        GH_TOKEN: ${{ secrets.HOMEBREW_TAP_TOKEN }}
        VERSION: ${{ inputs.version }}
        PACKAGE_URL: ${{ inputs.package_url }}
        PACKAGE_SHA256: ${{ inputs.package_sha256 }}
      run: |
        # Configure git
        git config --global user.name "Claude CTO Bot"
        git config --global user.email "bot@claude-cto.dev"
        
        # Clone the Homebrew tap repository
        git clone https://x-access-token:$GH_TOKEN@github.com/yigitkonur/homebrew-claude-cto.git tap
        cd tap
        
        # Create a branch for this update
        BRANCH_NAME="update-claude-cto-$VERSION"
        git checkout -b "$BRANCH_NAME"
        
        # Update the formula
        sed -i "s|url \".*\.tar\.gz\"|url \"$PACKAGE_URL\"|g" Formula/claude-cto.rb
        sed -i "s|sha256 \".*\"|sha256 \"$PACKAGE_SHA256\"|g" Formula/claude-cto.rb
        sed -i "s|claude-cto\[.*\]==.*\"|claude-cto[full]==$VERSION\"|g" Formula/claude-cto.rb
        sed -i "s|assert_match \"[0-9]\+\.[0-9]\+\"|assert_match \"$(echo $VERSION | cut -d. -f1).$(echo $VERSION | cut -d. -f2)\"|g" Formula/claude-cto.rb
        
        # Clear existing bottle block (if any)
        sed -i '/bottle do/,/end/d' Formula/claude-cto.rb
        
        # Check if there are changes
        if git diff --quiet; then
          echo "No changes needed - formula already up to date"
          exit 0
        fi
        
        # Commit changes
        git add Formula/claude-cto.rb
        git commit -m "Update claude-cto to $VERSION - Updated PyPI URL, SHA256, and version constraints - Auto-generated by GitHub Actions"
        git push origin "$BRANCH_NAME"
        
        # Create pull request
        curl -s -X POST \
          -H "Authorization: token $GH_TOKEN" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/yigitkonur/homebrew-claude-cto/pulls \
          -d "{\"title\": \"Update claude-cto to $VERSION\", \"head\": \"$BRANCH_NAME\", \"base\": \"main\", \"body\": \"Automated update to claude-cto $VERSION with PyPI URL $PACKAGE_URL and SHA256 $PACKAGE_SHA256\"}"
        
        echo "✅ Created pull request to update Homebrew formula to $VERSION"